<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Pandatech.CleanArchitecture.Core\Pandatech.CleanArchitecture.Core.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Auth\Application\"/>
    <Folder Include="Features\MyAccount\Application\"/>
    <Folder Include="Features\UserConfig\"/>
    <Folder Include="Features\User\Application\"/>
  </ItemGroup>
</Project>
