<Project Sdk="Microsoft.NET.Sdk">
    <Sdk Name="Microsoft.Build.CentralPackageVersions" Version="2.1.3"/>


    <ItemGroup>
        <PackageReference Include="Hangfire"/>
        <PackageReference Include="MassTransit.RabbitMQ"/>
        <PackageReference Include="Pandatech.CommissionCalculator"/>
        <PackageReference Include="Pandatech.Communicator"/>
        <PackageReference Include="Pandatech.MassTransit.PostgresOutbox"/>
        <PackageReference Include="Pandatech.SharedKernel"/>
        <PackageReference Include="Pandatech.SharedKernel.Postgres"/>
        <PackageReference Include="SonarAnalyzer.CSharp">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
